import * as React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { useQuery } from "@tanstack/react-query";




const Home: NextPage = () => {
  const [title, setTitle] = React.useState<string>('How inflation works explained');
  const [index, setIndex] = React.useState<string[]>([]);
  const { data, isLoading, error, refetch } = useQuery(['getScript'], () =>
    fetch(`/api/cohere/${title}`).then(res => res.json()), { enabled: false });


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-3">
        <input
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
        />
        <button
          className="bg-blue-400 p-2 rounded-md"
          onClick={() => refetch()}
        >
          Get Script Index
        </button>

      </main>
    </>
  );
};

export default Home;
