import * as React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const [title, setTitle] = React.useState<string>('How inflation works explained');
  const {
    data,
    isLoading,
    isFetched,
    isError,
    error,
    refetch
  } = api.cohere.generateScript.useQuery({ title }, { enabled: false });

  const handleClick = () => {
    refetch()
      .then(() => console.log(data))
      .catch((error) => console.log(error));
  };

  if (isError) {
    return <p>{error?.message}</p>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-3">
        <input
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
        />
        <button
          className="bg-blue-400 p-2 rounded-md"
          onClick={handleClick}
        >
          Get Script Index
        </button>
        {isLoading && <p>Loading...</p>}
        {isFetched && !isError && data && (
          <li className="list-none">
            {data.map((item, index) => (
              <p key={index}>{item}</p>
            ))}
          </li>
        )}
      </main>
    </>
  );
};

export default Home;
